name: Manual basic test agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-pirate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Ask pirate agent about shipments
        uses: ./
        with:
          agent: agentcatalog/pirate
          prompt: "What do we ship today?"
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
